### ISSUE TITLE
Dica para para que o gradiente fique por toda viewport na tag body

### ISSUE THREAD

**Issue by vtmx** [JonathanVasconcellos/japanesesMinigame#1]
Adicionando height 100vh em body, o gradiente irá ocupar toda a tela.

```css
body {
...
  height: 100vh;
...
}
```
